services:
  # MySQL数据库服务
  mysql:
    image: 'mysql:8.0'
    container_name: user-management-mysql
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network

  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
      - 'JWT_SECRET=YOUR_JWT_SECRET_KEY'
      - 'JWT_EXPIRATION=86400000'
      - 'SERVER_PORT=8080'
      # 邮件服务配置（需要替换为实际值）
      - 'SPRING_MAIL_HOST=smtp.example.com'
      - 'SPRING_MAIL_PORT=465'
      - 'SPRING_MAIL_USERNAME=YOUR_EMAIL'
      - 'SPRING_MAIL_PASSWORD=YOUR_EMAIL_PASSWORD'
      # GitHub OAuth2配置（需要替换为实际值）
      - 'SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID=YOUR_GITHUB_CLIENT_ID'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET=YOUR_GITHUB_CLIENT_SECRET'
    ports:
      - '8080:8080'
    restart: always
    networks:
      - app-network

# 定义持久化卷
volumes:
  mysql-data:
    driver: local

# 定义网络
networks:
  app-network:
    driver: bridge
